# Generated by Django 5.2.2 on 2025-06-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Для всех', 'Для всех'), ('16+', '16+'), ('18+', '18+')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MangaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('prodolzhaetsja', 'Продолжается'), ('zakonchen', 'Закончен'), ('zamorozhen', 'Заморожен'), ('neperevoditsjalitsenzirovano', 'Не переводится (лицензировано)'), ('netperevodchika', 'Нет переводчика')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('rating', models.FloatField(default=0)),
                ('year_released', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.agerating')),
                ('categories', models.ManyToManyField(to='manga.category')),
                ('genres', models.ManyToManyField(to='manga.genre')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangatype')),
            ],
        ),
    ]
